### ISSUE TITLE
API for csharp and python should be same 

### ISSUE THREAD

**Issue by Laeeth** [symmetryinvestments/autowrap#34]

**Comment by Laeeth** [comment]
```   Modules(
                    "prefix", "adder", "structs", "templates", "api",
                    Module("wrap_all") // , Yes.alwaysExport),
                ),
    ```

**Comment by atilaneves** [comment]
I'm not sure that making it exactly the same is possible. Or do you mean that `Yes.alwaysExport` should be an option?

**Comment by Laeeth** [comment]
Yes.alwaysExport should be an option and we should try to make API as similar as possible.  Should test wrapping for python, excel, csharp and SIL.  (SIL autowrap should run tests from public autowrap).  Otherwise we diverge and have strange bugs for no good reason.
